# Hexagon game Learner

Below is an implementation of the hexagon game written in a functional (stateless) style so that we can simulate actions in our Q-learner without changing the actual game board.

For storing the game board we use a numpy array instead of python lists, to make some of the operations less costly, as there is a lot of copying arrays going on.

In [25]:
import numpy as np
np.random.seed(0)

def randomGame(width, height):
    board = np.random.randint(5, size=(height + 1, width))
    
    # What we actually want is a jagged array where the odd cols 
    # are shifted half a cell up, to simulate a hexagon grid.
    # We achieve this by making the grid 1 higher than specified and 
    # 'remove' the top cell in the odd columns
    for x in range(width // 2):
        board[0][x * 2 + 1] = -1
        
    # Set the initial player positions
    board[0, 0] = 5
    board[height, width - 1] = 10
    
    return board

def getHash(board):
    # This function generates a unique hash for each board
    # This is done by realising that each cell on the board
    # can be in one of 7 (5 colors + owned by either player)
    # This means that each cell can be stored in a single character
    # 0-4 (colors), a (owned by player 1) and b (owned by player 2)
       
    lookUp = ['0', '1', '2', '3', '4', 'a', 'a', 'a', 'a', 'a', 'b', 'b', 'b', 'b', 'b', 'b', '']
    return ''.join([lookUp[int(i)] for i in np.nditer(board.T)])

def makeMove(board, player, action):
    # Do everything on a copy to ensure stateless-ness
    board = board.copy()
    
    height = board.shape[0]
    width = board.shape[1]
    
    frontier = getOwnedCells(board, player)
    
    # Our color can spread through cells that were just added
    # so we maintain a frontier that is the cells that we still
    # need to check for neighbors of the right colour
    while len(frontier):
        point = frontier.pop()
        board[point[0], point[1]] = action + player * 5
        
        neighbours = pointsAround(point)
        
        # Find the neighbours that are inside the board and
        # have the color of the action and add them to the frontier 
        for neighbour in neighbours:
            if (0 <= neighbour[0] < height 
                and 0 <= neighbour[1] < width 
                and board[neighbour[0], neighbour[1]] != -1 
                and board[neighbour[0], neighbour[1]] == action):
                frontier.append(neighbour)
    
    # If a player has no more moves, the other player is rewarded
    # the rest of the cells on the board
    board = finaliseBoard(board, player)
    return board

def getOwnedCells(board, player):
    lowerLimit = player * 5
    upperLimit = (player + 1) * 5
    
    frontier = list(
        np.column_stack(
            np.where(
                np.logical_and(board < upperLimit, board >= lowerLimit)
            )
        )
    )
    
    return frontier

def finaliseBoard(board, playerCall):
    board = board.copy()
    player = 2 if playerCall == 1 else 1
    frontier = getOwnedCells(board, player)
    height = board.shape[0]
    width = board.shape[1]
    
    playerColor = board[0, 0] if playerCall == 1 else board[height - 1, width - 1]
    found = False
    
    # Check if the player has a valid action that gains more cells
    for cell in frontier:
        neighbours = pointsAround(cell)
        for neighbour in neighbours:
            if (0 <= neighbour[0] < height 
                and 0 <= neighbour[1] < width 
                and 0 <= board[neighbour[0], neighbour[1]] < 5):
                found = True
                break
        if found:
            break
    if found:
        return board
    
    # Award the player the rest of the cells
    for x in np.nditer(board, op_flags=['readwrite']):
        if 0 <= int(x) < 5:
            x[...] = playerColor
    return board

def getReward(game, player):
    # This function calculates the reward of a game
    # We reward nothing for a move unless it is a winning move
    # Then it gains 1 point. If it is a losing move, it gains -1
    if not gameEnded(game):
        return -0.04

    height = game.shape[0]
    width = game.shape[1]
    
    player1Color = game[0,0]
    player2Color = game[height - 1, width - 1]
    player1count = np.count_nonzero(game == player1Color)
    player2count = np.count_nonzero(game == player2Color)
    
    if player == 1:
        if player1count > player2count:
            return 1
        else:
            return -1
    else:
        if player2count > player1count:
            return 1
        else:
            return -1

def gameEnded(board):
    # Simply checks if there are any cells that is not owned 
    return not np.any(np.logical_and(board >= 0, board < 5))
        
def pointsAround(point):
    y, x = point[0], point[1]
    relOddCoords = [
        (-1, 0),
        (-1, 1),
        (0, 1),
        (1, 0),
        (0, -1),
        (-1, -1)
    ]

    relEvenCoords = [
        (-1, 0),
        (0, 1),
        (1, 1),
        (1, 0),
        (1, -1),
        (0, -1)
    ]
    
    odd = x % 2 == 1
    
    neighbours = []
    for coord in relOddCoords if odd else relEvenCoords:
        newY = y + coord[0]
        newX = x + coord[1]
        neighbours.append([newY, newX])
    return neighbours


Below is an implementaiton of the Q-Learning-Agent from Russel & Norvig (2010) that maintains a State-Action array $Q$ and uses it to learns the best actions from the reward $r$ of a given state and action.

In [26]:
import json
import ast

def saveToFile(dict, fileName):
    with open(fileName, 'w') as fp:
        json.dump({str(k): v for k, v in dict.items()}, fp)

def loadFromFile(fileName):
    with open(fileName, 'r') as fp:
        return {ast.literal_eval(k): v for k, v in json.load(fp).items()}

class HexLearner(object):
    # This class is an implementation of the Q-Learning-Agent
    # from Russel & Norvig (2010) p. 844
    
    def __init__(self, player, Q = {}, N = {}):
        self.Q = Q
        self.N = N
        self.s = None
        self.hash = None
        self.a = None
        self.r = None
        self.player = player
        self.actions = [0, 1, 2, 3, 4]
        
    @classmethod
    def load(cls, player):
        return cls(player, loadFromFile("saves/P" + str(player) + "_Q.json"), loadFromFile("saves/P" + str(player) + "_N.json"))
    
    def save(self):
        saveToFile(latestQ1, "saves/P" + str(self.player) + "_Q.json")
        saveToFile(latestN1, "saves/P" + str(self.player) + "_N.json")
    
    def getMove(self, state, reward):
        if gameEnded(state):
            self.Q[getHash(state), None] = reward
        if self.s is not None:
            self.incrementN()
            self.updateQ(state, reward)
        self.s = state
        self.hash = getHash(state)
        self.a = self.argmax()
        self.r = reward
        return self.a
    
    def initializeQ(self, s, a):
        if (s, a) not in self.Q:
            self.Q[s, a] = 0
    
    def initializeN(self, s, a):
        if (s, a) not in self.N:
            self.N[s, a] = 0
    
    def argmax(self):
        vals = []
        s = self.hash
        vals = [self.f(self.Q.get((s, a), 0), self.N.get((s, a), 0)) for a in self.actions]
        return self.actions.index(vals.index(max(vals)))
    
    def f(self, val, num):
        if num < 10:
            return 100
        return val
    
    def incrementN(self):
        s = self.hash
        a = self.a
        self.initializeN(s, a)
        self.N[s, a] += 1
    
    def updateQ(self, sP, rP):
        s = self.hash
        sPh = getHash(sP)
        a = self.a
        self.initializeQ(s, a)
        self.Q[s, a] = self.Q[s, a] + self.alpha() * (self.r + max([self.Q.get((sPh, aP), 0) for aP in self.actions]) - self.Q[s, a])
        
    def alpha(self):
        return 60 / (59 + self.N[self.hash, self.a])

In [27]:
class GreedyHexAgent(object):
    def __init__(self, player):
        self.player = player
        self.actions = [0, 1, 2, 3, 4]
        
    def getMove(self, state, reward):
        numOwnedCell = [self.cellsOwned(makeMove(state, self.player, a)) for a in self.actions]
        return numOwnedCell.index(max(numOwnedCell))
        
    def cellsOwned(self, state):
        return getHash(state).count('a' if self.player == 1 else 'b')

In [65]:
class RandomAgent(object):
    def getMove(self, state, reward):
        return np.random.randint(5)

The agent is ready to learn! The code below lets the agent play against it self and learn along the way. We use a value $\varepsilon$ to denote the probability of choosing a random action instead of the action supplied by the agent. This is done to force the agent to explore more. $\alpha$

In [68]:
import time

np.random.seed(0)

NUMTRIALS = 10000
EPSILON = 0.1
latestQ1 = {}
latestN1 = {}
latestQ2 = {}
latestN2 = {}

startTime = time.time()
startGame = randomGame(3, 3)

for x in range(NUMTRIALS):
    agent1 = HexLearner(1, latestQ1, latestN1)
    agent2 = HexLearner(2, latestQ2, latestN2)
    game = randomGame(3,3)
    #game = startGame.copy()
    while not gameEnded(game):
        num = np.random.rand()
        action = agent1.getMove(game, getReward(game, 1))
        if num < EPSILON:
            action = np.random.randint(5)
        game = makeMove(game, 1, action)
        
        action = agent2.getMove(game, getReward(game, 2))
        if num < EPSILON:
            action = np.random.randint(5)
        game = makeMove(game, 2, action)
        
    agent1.getMove(game, getReward(game, 1))
    agent1.getMove(game, getReward(game, 1))
    agent2.getMove(game, getReward(game, 2))
    latestQ1 = agent1.Q
    latestN1 = agent1.N
    latestQ2 = agent2.Q
    latestN2 = agent2.N

agent1.save()
agent2.save()
print("\nDone! - Played " + str(NUMTRIALS) + " games. Took " + str(round(time.time() - startTime, 2)) + "s. Saw " + str(len(latestQ1)) + " states")


Done! - Played 10000 games. Took 93.55s. Saw 59880 states


## Battle of the centuries

In [69]:


GAMES = 10000



player1wins = 0
player2wins = 0
for x in range(GAMES):
    player1 = HexLearner(1, latestQ1, latestN1)
    player2 = GreedyHexAgent(2)
    game = randomGame(3, 3)
    while not gameEnded(game):
        action = player1.getMove(game, getReward(game, 1))
        game = makeMove(game, 1, action)
        if (gameEnded(game)):
            player1wins += 1
            continue
        action = player2.getMove(game, 0)
        game = makeMove(game, 2, action)
        if (gameEnded(game)):
            player2wins += 1

print("Player 1 wins: " + str(player1wins/GAMES*100) + "%")
print("Player 2 wins: " + str(player2wins/GAMES*100) + "%")

Player 1 wins: 13.200000000000001%
Player 2 wins: 86.8%


In [ ]:
print(latestQ1)

In [33]:
agent = GreedyHexAgent(1)
game = startGame.copy()
print(game)

while not gameEnded(game):
    action = agent.getMove(game, getReward(game, 1))
    if action != None:
        print("P1: " + str(action))
        game = makeMove(game, 1, action)
    print(game)
    
    game = makeMove(game, 2, int(input()))
    print(game)
print("P1 won!" if getReward(game, 1) == 1 else "P2 won!")

[[ 5 -1  3]
 [ 3  3  1]
 [ 3  2  4]
 [ 0  0 10]]
P1: 3
[[ 8 -1  8]
 [ 8  8  1]
 [ 8  2  4]
 [ 0  0 10]]
4
[[ 8 -1  8]
 [ 8  8  1]
 [ 8  2 14]
 [ 0  0 14]]
P1: 0
[[ 5 -1  5]
 [ 5  5  1]
 [ 5  2 14]
 [ 5  5 14]]
2
[[ 5 -1  5]
 [ 5  5  1]
 [ 5 12 12]
 [ 5  5 12]]
P1: 1
[[ 6 -1  6]
 [ 6  6  6]
 [ 6 12 12]
 [ 6  6 12]]


KeyboardInterrupt: 